version: '2.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    env_file:
    - kafka/kafka-variables.env
    depends_on:
    - zookeeper
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'

  consumer:
    build:
      context: consumer
    environment:
      kafkaURL: kafka:9092
      topic: topic1
      GroupID: logger-group
    depends_on: 
    - kafka

  producer:
    build:
      context: producer
    environment:
      kafkaURL: kafka:9092
      topic: topic1
    expose:
    - "8080"
    ports:
    - "8080:8080"
    depends_on: 
    - kafka